# Quick Start:
#
# pip install pre-commit
# pre-commit install && pre-commit install -t pre-push
# pre-commit run --all-files
#
# To Skip Checks:
#
# git commit --no-verify
fail_fast: false

default_language_version:
  python: python3.12

repos:
  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.259"
    hooks:
      - id: ruff

  # Black
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
